application: dnzo
version: 43
runtime: python
api_version: 1

handlers:  
- url: /stylesheets/(r[0-9]+/)?([^/]+\.css)
  static_files: stylesheets/\2
  upload:       stylesheets/(.+\.css)
  expiration:   365d
  
- url: /javascripts/(r[0-9]+/)?([^/]+\.js)
  static_files: javascripts/\2
  upload:       javascripts/(.+\.js)
  expiration:   365d
  
- url: /images
  static_dir: images
  expiration: 30d
 
- url: /(robots.txt|favicon.ico)
  static_files: \1
  upload: (robots.txt|favicon.ico)
 
- url: /admin/.*
  script: main.py
  login: admin
  
- url: /
  script: main.py
  
- url: /.+
  script: main.py
  login: required
