application: dnzo
version: 297
runtime: python
api_version: 1

handlers:  
- url: /stylesheets/(r[0-9]+/)?([^/]+\.css)
  static_files: resources/stylesheets/\2
  upload:       resources/stylesheets/(.+\.css)
  expiration:   365d
  
- url: /javascripts/(r[0-9]+/)?([\w/]+\.js)
  static_files: resources/javascripts/\2
  upload:       resources/javascripts/(.+\.js)
  expiration:   365d
  
- url: /(robots.txt|favicon.ico)
  static_files: resources/\1
  upload:       resources/(robots.txt|favicon.ico)
  expiration:   365d
  
- url: /images
  static_dir: resources/images
  expiration: 30d

- url: /api/.+
  script: api/main.py
  #login: required

- url: /admin/.+
  script: common/appenginepatch/main.py
  login:  admin
  
- url: /
  script: common/appenginepatch/main.py
  
- url: /.+
  script: common/appenginepatch/main.py
  login:  required